image: ubuntu:18.10

before_script:
  - apt-get -y update
  - apt-get -y install
      intltool
      libglib2.0-dev
      libgtk-3-dev
      libgcrypt20-dev
      nettle-dev
      libb2-dev
      libmbedtls-dev
      libmhash-dev
      linux-libc-dev
      librsvg2-bin
      at-spi2-core
      xvfb
      libnautilus-extension-dev
      libnemo-extension-dev
      libcaja-extension-dev
      libthunarx-3-dev
      libpeony-extension-dev

gtkhash:
  script:
    - ./autogen.sh
    - export DISTCHECK_CONFIGURE_FLAGS=$(echo
        --enable-debug
        --enable-blake2
        --enable-gcrypt
        --enable-glib-checksums
        --enable-mbedtls
        --enable-mhash
        --enable-nettle
        --enable-linux-crypto
        --enable-nautilus
        --enable-nemo
        --enable-caja
        --enable-thunar
        --enable-peony
        --disable-dependency-tracking
      )
    - ./configure ${DISTCHECK_CONFIGURE_FLAGS}
    - make -j$(nproc) VERBOSE=1 DESTDIR=$(mktemp -d) distcheck

  artifacts:
    paths:
      - gtkhash-*.tar.gz
      - gtkhash-*.tar.xz
